/**
 * NOTE: This class is auto generated by the akka-scala (beta) swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * For any issue or feedback, please open a ticket via https://github.com/swagger-api/swagger-codegen/issues/new
 */
package io.swagger.client.api

import io.swagger.client.model.Produce
import io.swagger.client.core._
import io.swagger.client.core.CollectionFormats._
import io.swagger.client.core.ApiKeyLocations._

object ProduceApi {

  /**
   * 
   * Expected answers:
   *   code 405 :  (Invalid input)
   * 
   * @param body Add a new produce to the produce database
   */
  def addproduce(body: Produce): ApiRequest[Unit] =
    ApiRequest[Unit](ApiMethods.POST, "https://virtserver.swaggerhub.com/gatheringfarm/Produce/v1", "/produce", "application/json")
      .withBody(body)
      .withErrorResponse[Unit](405)
        /**
   * 
   * Expected answers:
   *   code 400 :  (Invalid ID supplied)
   *   code 404 :  (produce not found)
   *   code 405 :  (Validation exception)
   * 
   * @param body Updates an existing produce
   */
  def updateproduce(body: Produce): ApiRequest[Unit] =
    ApiRequest[Unit](ApiMethods.PUT, "https://virtserver.swaggerhub.com/gatheringfarm/Produce/v1", "/produce", "application/json")
      .withBody(body)
      .withErrorResponse[Unit](400)
      .withErrorResponse[Unit](404)
      .withErrorResponse[Unit](405)
      

}

