/**
 * NOTE: This class is auto generated by the akka-scala (beta) swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * For any issue or feedback, please open a ticket via https://github.com/swagger-api/swagger-codegen/issues/new
 */

package io.swagger.client.model

import io.swagger.client.core.ApiModel
import org.joda.time.DateTime
import java.util.UUID

case class Calendar (
  id: Option[Long],
  calendar: Option[CalendarEnums.Calendar],
  january: Option[Boolean],
  february: Option[Boolean],
  march: Option[Boolean],
  april: Option[Boolean],
  may: Option[Boolean],
  june: Option[Boolean],
  july: Option[Boolean],
  august: Option[Boolean],
  september: Option[Boolean],
  october: Option[Boolean],
  november: Option[Boolean],
  december: Option[Boolean]
) extends ApiModel

object CalendarEnums {

  type Calendar = Calendar.Value
  object Calendar extends Enumeration {
    val SowIndoors = Value("sow indoors")
    val SowOutdoorsDirect = Value("sow outdoors direct")
    val SowOutdoorsUndercover = Value("sow outdoors undercover")
    val TransplantOutdoorsDirect = Value("transplant outdoors direct")
    val TransplantOutdoorsUndercover = Value("transplant outdoors undercover")
    val Harvest = Value("harvest")
    val CollectSeed = Value("collect seed")
  }

}

