/**
 * NOTE: This class is auto generated by the akka-scala (beta) swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * For any issue or feedback, please open a ticket via https://github.com/swagger-api/swagger-codegen/issues/new
 */

package io.swagger.client.model

import io.swagger.client.core.ApiModel
import org.joda.time.DateTime
import java.util.UUID

case class Variety (
  id: Option[Long],
  image: Option[String],
  latinName: Option[String],
  description: Option[String],
  vendor: Option[String],
  price: Option[String],
  link: Option[String]
) extends ApiModel


